<a href="https://colab.research.google.com/github/asheldrick-research/ecsm-framework/blob/main/ECSM_Electron_Like_Packet_Frozen_Measured_Scattering_Confrontation_Protocol_V35_CLEAN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ECSM Electron-Like Packet — Frozen Measured-Scattering Confrontation Protocol V35

This notebook does **not** ingest measured scattering data. It freezes the confrontation rules for V36 before any measured-data comparison is run.

## Cell 1 — Setup and fixed output path

In [1]:
from pathlib import Path
import json, zipfile
import pandas as pd

if Path("/content").exists():
    BASE = Path("/content")
else:
    BASE = Path("/mnt/data")

OUT = BASE / "ecsm_electron_like_frozen_measured_scattering_protocol_v35_out"
OUT.mkdir(parents=True, exist_ok=True)
print("Output directory:", OUT)

Output directory: /content/ecsm_electron_like_frozen_measured_scattering_protocol_v35_out

## Cell 2 — Frozen protocol definition

In [2]:
protocol = {
  "run_label": "V35_frozen_measured_scattering_confrontation_protocol",
  "protocol_label": "FROZEN_MEASURED_SCATTERING_CONFRONTATION_PROTOCOL_READY",
  "purpose": "Define a frozen, no-retuning protocol for the first measured scattering-data confrontation of the ECSM electron-like packet.",
  "status": "protocol_only_no_measured_data_ingested",
  "frozen_inherited_values": {
    "source_chain": "V21b -> V22 -> V23 -> V24 -> V25 -> V26 -> V27 -> V27b -> V28 -> V29 -> V30 -> V31 -> V32 -> V33 -> V34",
    "q_eff": -0.9993035720499918,
    "E_rest_keV_from_V21b": 514.0698767738036,
    "alpha_fs_input": 0.0072973525692838015,
    "k_response_keV": 5140.698767738036,
    "r_rms_response_fm_from_V34": 38.385244752791856,
    "Pi_ecsm_plateau_locked": 0.007146727844882419,
    "form_factor": "F(q)=exp[-(q/k_response)^2/6]"
  },
  "allowed_observables": [
    "shape-normalised elastic electron scattering angular distributions",
    "cross-section ratios normalised to a declared reference angle or bin",
    "low-transfer slope/shape residuals over pre-declared q range",
    "large-angle finite-suppression ratios over pre-declared q range"
  ],
  "forbidden_observables_for_first_confrontation": [
    "absolute luminosity-normalised cross sections requiring experiment-specific detector calibration modelling",
    "datasets requiring nuclear-structure deconvolution as the dominant uncertainty",
    "data requiring post-hoc selection after looking at fit quality",
    "high-energy regimes requiring a full renormalised QED S-matrix beyond the present ECSM claim boundary"
  ],
  "admissible_dataset_rules": [
    "dataset must be publicly accessible or supplied as a static file before running the confrontation notebook",
    "dataset metadata must include beam energy or momentum, scattering angle or q-transfer, observable value, and uncertainty or declared reason for unweighted comparison",
    "all cleaning rules must be declared before computing ECSM residuals",
    "data may be excluded only by pre-declared physical/domain criteria, not by residual size",
    "one primary dataset must be declared before any comparison; optional secondary datasets must be marked as replication checks"
  ],
  "frozen_model_rules": {
    "no_retuning": [
      "q_eff",
      "E_rest_keV",
      "alpha_fs",
      "k_response_keV",
      "r_rms_response_fm",
      "form_factor_shape",
      "running_response_plateau",
      "normalisation convention once selected"
    ],
    "allowed_operations": [
      "unit conversion",
      "angle-to-q conversion using declared kinematics",
      "global shape normalisation fixed by a pre-declared reference bin/angle",
      "masking by pre-declared energy/q/angle domain",
      "uncertainty propagation using supplied uncertainties"
    ],
    "forbidden_operations": [
      "fitting k_response to measured data",
      "fitting the Gaussian exponent or replacing the form factor after seeing residuals",
      "changing q_eff, E_rest, alpha_fs, or Pi_ecsm_plateau",
      "choosing comparison window after viewing residuals",
      "dropping outlier points based on ECSM residuals",
      "claiming full QED scattering, precision Mott/Rutherford prediction, or measured electron radius"
    ]
  },
  "predeclared_primary_domain": {
    "q_min_keV": 0.0,
    "q_max_keV": 1268.2050944324717,
    "purpose": "first confrontation focuses on the V33/V34 low-transfer shape-retention regime",
    "reason": "V33 explicitly resolved the V32 low-transfer shape tension under locked theoretical-reference tests"
  },
  "predeclared_secondary_domain": {
    "q_min_keV": 1268.2050944324717,
    "q_max_keV": 10979.69097571184,
    "purpose": "large-angle/high-transfer finite-suppression replication check",
    "reason": "V33/V34 retained finite suppression at the fixed-grid qmax"
  },
  "verdict_thresholds": {
    "PASS": [
      "primary-domain mean relative shape residual <= 0.05, or weighted reduced chi2 <= 2 if uncertainties are reliable",
      "primary-domain maximum relative shape residual <= 0.20 unless documented experimental uncertainty is larger",
      "no forbidden parameter adjustment",
      "large-angle response remains finite in declared secondary check"
    ],
    "PARTIAL_PASS": [
      "primary-domain mean relative shape residual <= 0.15, or weighted reduced chi2 <= 5 if uncertainties are reliable",
      "clear qualitative shape agreement but at least one strict threshold fails",
      "no forbidden parameter adjustment"
    ],
    "FAIL": [
      "primary-domain mean relative shape residual > 0.15, or weighted reduced chi2 > 5 if uncertainties are reliable",
      "systematic shape disagreement in the declared primary domain",
      "any required model repair would alter frozen values or form-factor shape"
    ],
    "INVALID": [
      "measured data used before protocol freeze",
      "dataset or domain changed after viewing residuals",
      "forbidden parameter adjustment performed",
      "insufficient metadata to compute declared observable"
    ]
  },
  "claim_boundary": [
    "V35 is a protocol paper/notebook only.",
    "It does not compare to measured scattering data.",
    "It does not claim a measured electron charge radius.",
    "It does not claim full QED scattering or a renormalised S-matrix.",
    "It prepares V36 as a falsifiable external confrontation."
  ]
}
(OUT / "v35_frozen_measured_scattering_protocol.json").write_text(json.dumps(protocol, indent=2))
print(json.dumps(protocol, indent=2))

{
  "run_label": "V35_frozen_measured_scattering_confrontation_protocol",
  "protocol_label": "FROZEN_MEASURED_SCATTERING_CONFRONTATION_PROTOCOL_READY",
  "purpose": "Define a frozen, no-retuning protocol for the first measured scattering-data confrontation of the ECSM electron-like packet.",
  "status": "protocol_only_no_measured_data_ingested",
  "frozen_inherited_values": {
    "source_chain": "V21b -> V22 -> V23 -> V24 -> V25 -> V26 -> V27 -> V27b -> V28 -> V29 -> V30 -> V31 -> V32 -> V33 -> V34",
    "q_eff": -0.9993035720499918,
    "E_rest_keV_from_V21b": 514.0698767738036,
    "alpha_fs_input": 0.0072973525692838015,
    "k_response_keV": 5140.698767738036,
    "r_rms_response_fm_from_V34": 38.385244752791856,
    "Pi_ecsm_plateau_locked": 0.007146727844882419,
    "form_factor": "F(q)=exp[-(q/k_response)^2/6]"
  },
  "allowed_observables": [
    "shape-normalised elastic electron scattering angular distributions",
    "cross-section ratios normalised to a declared reference angle or bin",
    "low-transfer slope/shape residuals over pre-declared q range",
    "large-angle finite-suppression ratios over pre-declared q range"
  ],
  "forbidden_observables_for_first_confrontation": [
    "absolute luminosity-normalised cross sections requiring experiment-specific detector calibration modelling",
    "datasets requiring nuclear-structure deconvolution as the dominant uncertainty",
    "data requiring post-hoc selection after looking at fit quality",
    "high-energy regimes requiring a full renormalised QED S-matrix beyond the present ECSM claim boundary"
  ],
  "admissible_dataset_rules": [
    "dataset must be publicly accessible or supplied as a static file before running the confrontation notebook",
    "dataset metadata must include beam energy or momentum, scattering angle or q-transfer, observable value, and uncertainty or declared reason for unweighted comparison",
    "all cleaning rules must be declared before computing ECSM residuals",
    "data may be excluded only by pre-declared physical/domain criteria, not by residual size",
    "one primary dataset must be declared before any comparison; optional secondary datasets must be marked as replication checks"
  ],
  "frozen_model_rules": {
    "no_retuning": [
      "q_eff",
      "E_rest_keV",
      "alpha_fs",
      "k_response_keV",
      "r_rms_response_fm",
      "form_factor_shape",
      "running_response_plateau",
      "normalisation convention once selected"
    ],
    "allowed_operations": [
      "unit conversion",
      "angle-to-q conversion using declared kinematics",
      "global shape normalisation fixed by a pre-declared reference bin/angle",
      "masking by pre-declared energy/q/angle domain",
      "uncertainty propagation using supplied uncertainties"
    ],
    "forbidden_operations": [
      "fitting k_response to measured data",
      "fitting the Gaussian exponent or replacing the form factor after seeing residuals",
      "changing q_eff, E_rest, alpha_fs, or Pi_ecsm_plateau",
      "choosing comparison window after viewing residuals",
      "dropping outlier points based on ECSM residuals",
      "claiming full QED scattering, precision Mott/Rutherford prediction, or measured electron radius"
    ]
  },
  "predeclared_primary_domain": {
    "q_min_keV": 0.0,
    "q_max_keV": 1268.2050944324717,
    "purpose": "first confrontation focuses on the V33/V34 low-transfer shape-retention regime",
    "reason": "V33 explicitly resolved the V32 low-transfer shape tension under locked theoretical-reference tests"
  },
  "predeclared_secondary_domain": {
    "q_min_keV": 1268.2050944324717,
    "q_max_keV": 10979.69097571184,
    "purpose": "large-angle/high-transfer finite-suppression replication check",
    "reason": "V33/V34 retained finite suppression at the fixed-grid qmax"
  },
  "verdict_thresholds": {
    "PASS": [
      "primary-domain mean relative shape residual <= 0.05, or weighted reduced chi2 <= 2 if uncertainties are reliable",
      "primary-domain maximum relative shape residual <= 0.20 unless documented experimental uncertainty is larger",
      "no forbidden parameter adjustment",
      "large-angle response remains finite in declared secondary check"
    ],
    "PARTIAL_PASS": [
      "primary-domain mean relative shape residual <= 0.15, or weighted reduced chi2 <= 5 if uncertainties are reliable",
      "clear qualitative shape agreement but at least one strict threshold fails",
      "no forbidden parameter adjustment"
    ],
    "FAIL": [
      "primary-domain mean relative shape residual > 0.15, or weighted reduced chi2 > 5 if uncertainties are reliable",
      "systematic shape disagreement in the declared primary domain",
      "any required model repair would alter frozen values or form-factor shape"
    ],
    "INVALID": [
      "measured data used before protocol freeze",
      "dataset or domain changed after viewing residuals",
      "forbidden parameter adjustment performed",
      "insufficient metadata to compute declared observable"
    ]
  },
  "claim_boundary": [
    "V35 is a protocol paper/notebook only.",
    "It does not compare to measured scattering data.",
    "It does not claim a measured electron charge radius.",
    "It does not claim full QED scattering or a renormalised S-matrix.",
    "It prepares V36 as a falsifiable external confrontation."
  ]
}

## Cell 3 — Criteria audit and verdict

In [3]:
criteria = [
    ("inherits V21b-V34 frozen packet chain", 1.0, True),
    ("q_eff frozen", abs(abs(protocol["frozen_inherited_values"]["q_eff"]) - 1.0), True),
    ("E_rest frozen", protocol["frozen_inherited_values"]["E_rest_keV_from_V21b"], True),
    ("alpha_fs frozen", protocol["frozen_inherited_values"]["alpha_fs_input"], True),
    ("k_response frozen", protocol["frozen_inherited_values"]["k_response_keV"], True),
    ("r_rms_response frozen", protocol["frozen_inherited_values"]["r_rms_response_fm_from_V34"], True),
    ("form-factor shape frozen", 1.0, True),
    ("primary q-domain predeclared", protocol["predeclared_primary_domain"]["q_max_keV"], True),
    ("secondary q-domain predeclared", protocol["predeclared_secondary_domain"]["q_max_keV"], True),
    ("allowed observables declared", len(protocol["allowed_observables"]), True),
    ("forbidden observables declared", len(protocol["forbidden_observables_for_first_confrontation"]), True),
    ("dataset admissibility rules declared", len(protocol["admissible_dataset_rules"]), True),
    ("allowed operations declared", len(protocol["frozen_model_rules"]["allowed_operations"]), True),
    ("forbidden operations declared", len(protocol["frozen_model_rules"]["forbidden_operations"]), True),
    ("PASS thresholds declared", len(protocol["verdict_thresholds"]["PASS"]), True),
    ("PARTIAL_PASS thresholds declared", len(protocol["verdict_thresholds"]["PARTIAL_PASS"]), True),
    ("FAIL thresholds declared", len(protocol["verdict_thresholds"]["FAIL"]), True),
    ("INVALID conditions declared", len(protocol["verdict_thresholds"]["INVALID"]), True),
    ("no measured data ingested", 0.0, True),
    ("no parameters adjusted after comparison", 0.0, True),
    ("failure allowed by protocol", 1.0, True),
]
criteria_df = pd.DataFrame(criteria, columns=["criterion", "value", "pass"])
criteria_df.to_csv(OUT / "v35_frozen_measured_scattering_protocol_criteria.csv", index=False)
n_pass, n_criteria = int(criteria_df["pass"].sum()), len(criteria_df)
final_label = "PASS_FROZEN_MEASURED_SCATTERING_PROTOCOL_READY" if n_pass == n_criteria else "FAIL_PROTOCOL_INCOMPLETE"
run_summary = {
    "run_label": protocol["run_label"],
    "final_label": final_label,
    "n_pass": n_pass,
    "n_criteria": n_criteria,
    "status": "protocol_only_no_measured_data_ingested",
    "next_step": "V36_first_frozen_measured_scattering_data_confrontation",
    "primary_q_max_keV": protocol["predeclared_primary_domain"]["q_max_keV"],
    "secondary_q_max_keV": protocol["predeclared_secondary_domain"]["q_max_keV"],
    "frozen_k_response_keV": protocol["frozen_inherited_values"]["k_response_keV"],
    "frozen_r_rms_response_fm": protocol["frozen_inherited_values"]["r_rms_response_fm_from_V34"],
    "measured_data_used": False,
    "parameters_adjusted_after_comparison": False,
    "notes": "V35 freezes the measured-data confrontation rules before any V36 measured-data comparison."
}
(OUT / "run_summary_v35.json").write_text(json.dumps(run_summary, indent=2))
pd.DataFrame([run_summary]).to_csv(OUT / "final_v35_protocol_verdict.csv", index=False)
print("Final label:", final_label)
print(json.dumps(run_summary, indent=2))
display(criteria_df)

Final label: PASS_FROZEN_MEASURED_SCATTERING_PROTOCOL_READY
{
  "run_label": "V35_frozen_measured_scattering_confrontation_protocol",
  "final_label": "PASS_FROZEN_MEASURED_SCATTERING_PROTOCOL_READY",
  "n_pass": 21,
  "n_criteria": 21,
  "status": "protocol_only_no_measured_data_ingested",
  "next_step": "V36_first_frozen_measured_scattering_data_confrontation",
  "primary_q_max_keV": 1268.2050944324717,
  "secondary_q_max_keV": 10979.69097571184,
  "frozen_k_response_keV": 5140.698767738036,
  "frozen_r_rms_response_fm": 38.385244752791856,
  "measured_data_used": false,
  "parameters_adjusted_after_comparison": false,
  "notes": "V35 freezes the measured-data confrontation rules before any V36 measured-data comparison."
}

                                  criterion         value  pass
0     inherits V21b-V34 frozen packet chain      1.000000  True
1                              q_eff frozen      0.000696  True
2                             E_rest frozen    514.069877  True
3                           alpha_fs frozen      0.007297  True
4                         k_response frozen   5140.698768  True
5                     r_rms_response frozen     38.385245  True
6                  form-factor shape frozen      1.000000  True
7              primary q-domain predeclared   1268.205094  True
8            secondary q-domain predeclared  10979.690976  True
9              allowed observables declared      4.000000  True
10           forbidden observables declared      4.000000  True
11     dataset admissibility rules declared      5.000000  True
12              allowed operations declared      5.000000  True
13            forbidden operations declared      6.000000  True
14                 PASS thresholds declared      4.000000  True
15         PARTIAL_PASS thresholds declared      3.000000  True
16                 FAIL thresholds declared      3.000000  True
17              INVALID conditions declared      4.000000  True
18                no measured data ingested      0.000000  True
19  no parameters adjusted after comparison      0.000000  True
20              failure allowed by protocol      1.000000  True

## Cell 4 — Export manifest and ZIP

In [4]:
manifest = pd.DataFrame({"file": sorted([p.name for p in OUT.iterdir()])})
manifest.to_csv(OUT / "output_manifest_v35.csv", index=False)

zip_path = BASE / "ecsm_electron_like_frozen_measured_scattering_protocol_v35_out.zip"
if zip_path.exists():
    zip_path.unlink()
with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as z:
    for p in OUT.iterdir():
        z.write(p, arcname=p.name)

print("Output directory:", OUT)
print("Zip file:", zip_path)
display(manifest)

Output directory: /content/ecsm_electron_like_frozen_measured_scattering_protocol_v35_out
Zip file: /content/ecsm_electron_like_frozen_measured_scattering_protocol_v35_out.zip

                                                file
0                     final_v35_protocol_verdict.csv
1                               run_summary_v35.json
2       v35_frozen_measured_scattering_protocol.json
3  v35_frozen_measured_scattering_protocol_criter...

## Cell 5 — Verification

In [5]:
required = [
    "v35_frozen_measured_scattering_protocol.json",
    "v35_frozen_measured_scattering_protocol_criteria.csv",
    "run_summary_v35.json",
    "final_v35_protocol_verdict.csv",
    "output_manifest_v35.csv",
]
for name in required:
    print(name, "exists:", (OUT / name).exists())
display(pd.read_csv(OUT / "v35_frozen_measured_scattering_protocol_criteria.csv"))
print(json.dumps(json.loads((OUT / "run_summary_v35.json").read_text()), indent=2))

v35_frozen_measured_scattering_protocol.json exists: True
v35_frozen_measured_scattering_protocol_criteria.csv exists: True
run_summary_v35.json exists: True
final_v35_protocol_verdict.csv exists: True
output_manifest_v35.csv exists: True

                                  criterion         value  pass
0     inherits V21b-V34 frozen packet chain      1.000000  True
1                              q_eff frozen      0.000696  True
2                             E_rest frozen    514.069877  True
3                           alpha_fs frozen      0.007297  True
4                         k_response frozen   5140.698768  True
5                     r_rms_response frozen     38.385245  True
6                  form-factor shape frozen      1.000000  True
7              primary q-domain predeclared   1268.205094  True
8            secondary q-domain predeclared  10979.690976  True
9              allowed observables declared      4.000000  True
10           forbidden observables declared      4.000000  True
11     dataset admissibility rules declared      5.000000  True
12              allowed operations declared      5.000000  True
13            forbidden operations declared      6.000000  True
14                 PASS thresholds declared      4.000000  True
15         PARTIAL_PASS thresholds declared      3.000000  True
16                 FAIL thresholds declared      3.000000  True
17              INVALID conditions declared      4.000000  True
18                no measured data ingested      0.000000  True
19  no parameters adjusted after comparison      0.000000  True
20              failure allowed by protocol      1.000000  True

{
  "run_label": "V35_frozen_measured_scattering_confrontation_protocol",
  "final_label": "PASS_FROZEN_MEASURED_SCATTERING_PROTOCOL_READY",
  "n_pass": 21,
  "n_criteria": 21,
  "status": "protocol_only_no_measured_data_ingested",
  "next_step": "V36_first_frozen_measured_scattering_data_confrontation",
  "primary_q_max_keV": 1268.2050944324717,
  "secondary_q_max_keV": 10979.69097571184,
  "frozen_k_response_keV": 5140.698767738036,
  "frozen_r_rms_response_fm": 38.385244752791856,
  "measured_data_used": false,
  "parameters_adjusted_after_comparison": false,
  "notes": "V35 freezes the measured-data confrontation rules before any V36 measured-data comparison."
}